version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: epass-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secretpassword
    volumes:
      - mongo_data:/data/db

  explorer:
    image: abdullahmia/compooss:latest
    container_name: mongo_explorer
    ports:
      - "6969:3000"
    depends_on:
      - mongodb

volumes:
  mongo_data: