name: Web App Build CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Web App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 11

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'src/epass-web/pnpm-lock.yaml'

      - name: Install dependencies
        run: |
          cd src/epass-web
          pnpm install

      - name: Build Next.js Web App
        run: |
          cd src/epass-web
          pnpm build
